# Nightly benchmark config.
[remote]
host = "bencher16.soft-dev.org"
user = "pd"
root = "/home/pd/nightly-haste"

# Each [[targets]] block is one repo/ref pairing to build and benchmark.

[[targets]]
name     = "yksompp-fork"
repo     = "git@github.com:Pavel-Durov/yksompp-fork.git"
ref      = "main"
build    = "just yk_config=/home/pd/yk/bin/yk-config build-yk-release"
template = "som"
env.EXE     = "/home/pd/nightly-haste/yksompp-fork/cmake-yk-release/SOM++"
env.SOM_LIB = "/home/pd/nightly-haste/yksompp-fork/Smalltalk"

[[targets]]
name     = "yksompp-fork_yk-anotations-ms-gc"
repo     = "git@github.com:Pavel-Durov/yksompp-fork.git"
ref      = "yk-anotations-ms-gc"
build    = "just yk_config=/home/pd/yk/bin/yk-config build-yk-release"
template = "som"
env.EXE     = "/home/pd/nightly-haste/yksompp-fork_yk-anotations-ms-gc/cmake-yk-release/SOM++"
env.SOM_LIB = "/home/pd/nightly-haste/yksompp-fork_yk-anotations-ms-gc/Smalltalk"

[[targets]]
name     = "SOMpp"
repo     = "git@github.com:SOM-st/SOMpp.git"
ref      = "master"
build    = "mkdir -p cmake-build && cd cmake-build && cmake -DCMAKE_BUILD_TYPE=Release .. && make"
template = "som"
env.EXE     = "/home/pd/nightly-haste/SOMpp/cmake-build/SOM++"
env.SOM_LIB = "/home/pd/nightly-haste/SOMpp/Smalltalk"

[[targets]]
name     = "SOMpp_ms-gc"
repo     = "git@github.com:Pavel-Durov/yksompp-fork.git"
ref      = "mark-and-sweep-gc-as-default"
build    = "mkdir -p cmake-build && cd cmake-build && cmake -DCMAKE_BUILD_TYPE=Release .. && make"
template = "som"
env.EXE     = "/home/pd/nightly-haste/SOMpp_ms-gc/cmake-build/SOM++"
env.SOM_LIB = "/home/pd/nightly-haste/SOMpp_ms-gc/Smalltalk"

[[targets]]
name     = "ykmicropython"
repo     = "git@github.com:ykjit/ykmicropython.git"
ref      = "master"
build    = "make -C mpy-cross && cd ports/unix && make submodules && PATH=/home/pd/yk/bin:$PATH YK_BUILD_TYPE=release make V=1"
template = "python"
env.EXE = "/home/pd/nightly-haste/ykmicropython/ports/unix/build-standard/micropython"

[[targets]]
name     = "ykmicropython_emitbc-jit-loop-locations"
repo     = "git@github.com:Pavel-Durov/ykmicropython-fork.git"
ref      = "emitbc-jit-loop-locations"
build    = "make -C mpy-cross && cd ports/unix && make submodules && PATH=/home/pd/yk/bin:$PATH YK_BUILD_TYPE=release make V=1"
template = "python"
env.EXE = "/home/pd/nightly-haste/ykmicropython_emitbc-jit-loop-locations/ports/unix/build-standard/micropython"
